// Code generated by Slice Machine. DO NOT EDIT.

import AboutSlice from './AboutSlice';
import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';

export {
	AboutSlice,
	HeroSlice,
	ImageGrid,
};

export const components = {
	about_slice: AboutSlice,
	textblock: HeroSlice,
	image_grid: ImageGrid,
};
